### PR TITLE
set puppet_etcdir of foreman module

### PR DESCRIPTION
**Pull request by mmoll**
this will put the correct etc_dir into the foreman module config

to be used together with theforeman/puppet-foreman#413

### CODE REVIEW

**Comment by brandonweeks** [comment]
Tested with Puppet 4. :+1:

**Comment by ekohl** [comment]
Thanks! We should remember to bump the required version of puppet-foreman when releasing.

**Comment by domcleal** [comment]
There's no dependency on puppet-foreman here, the only thing we might want to add is that puppet-foreman must be >= 5.0.0 in the README.

**Comment by ekohl** [comment]
That's a good point. Actually for AIO installs it needs https://github.com/theforeman/puppet-foreman/commit/e14c941a2d543f7ba4144ecda5bb6aec4335bb6d which is not yet in a released version.

@mmoll what happens on FreeBSD? I think it now places that config in /usr/local/puppet/etc/foreman.yaml but the script doesn't look for it in that location.

**Comment by mmoll** [comment]
@ekohl it does, as this is the wanted location for it: https://github.com/theforeman/puppet-foreman/blob/master/files/foreman-report_v2.rb#L27-L29 :)

**Comment by ekohl** [comment]
Right :)

**Pull request merged**
