### PR TITLE
Update acceptance tests

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by domcleal** [comment]
Can you resolve the merge conflict?

**Comment by ekohl** [comment]
Updated. I left out Debian tests for now because they fail on the upgrade because those versions are not available to install.

**Comment by mmoll** [comment]
versions of puppetserver?

**Comment by ekohl** [comment]
> versions of puppetserver?

The upgrade integration test installs 2.6.0 and then upgrades to 2.7.2. Those versions weren't installable in the container I tried with. I haven't looked at the logs, but my suspicion is that those versions aren't in the Debian repo (anymore).

**Comment by domcleal** [comment]
I think they are, but the full version suffix may be required (`2.7.0-1puppetlabs1`) for the package provider and apt to install them. At worst, the upgrade test could be skipped on Debian-based OSes but the regular installation could be enabled?

**Comment by ekohl** [comment]
You are correct that it needs to be the full version. Updated the test.

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
