### PR TITLE
Contain classes

### PR DESCRIPTION
**Pull request by ekohl**
This is the current way of containing classes

### CODE REVIEW

**Comment by ekohl** [comment]
You're right. I partially did it but now at least with classes we're consistently not using them. Changing all the variables is another (big) patch so I'm leaving that out here.

**Comment by mmoll** [comment]
@ekohl please rebase :)

**Comment by ekohl** [comment]
Rebased

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
