### PR TITLE
Drop listen parameter

### PR DESCRIPTION
**Pull request by ekohl**
Puppet 4 dropped puppet run/kick so this code has been dead for some time. It was missed in the big Puppet cleanups.

### CODE REVIEW

**Comment by ekohl** [comment]
Technically this is breaking though few users should be affected.

**Comment by mmoll** [comment]
:broken_heart:

**Comment by ekohl** [comment]
Looks like I missed the actual parameters.

**Comment by ekohl** [comment]
:green_heart:

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
