### PR TITLE
add puppetserver 2.7.x support

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
@ekohl It does indeed copy the default and the difference in 2.7 is that one can turn it off now. On the other hand, we would be free to change it, I guess... and I would also vote for disabling it.

**Comment by mmoll** [comment]
@domcleal any opinion on disabling the update check per default?

**Comment by domcleal** [comment]
I think it's important for the module to reflect the defaults as closely as possible, so I think it needs to remain true. (Even if I dislike it.)

**Comment by ekohl** [comment]
Looks like we're all in agreement then: we dislike the default but it is the default and the module should have no bias.

**Comment by domcleal** [comment]
Thanks @mmoll.

**Pull request merged**
