### PR TITLE
Reset environment to 'production' while proxing CA requests.

### PR DESCRIPTION
**Pull request by aleksey-novikov**
This changes make it possible do not deploy environments used on master to proxed CA

### CODE REVIEW

**Comment by mmoll** [comment]
@aleksey-novikov could you provide a bit more background on this change? Also, if you need to change something in an open PR, please re-use the existing one.

**Comment by aleksey-novikov** [comment]
I have some Puppet Masters (currently 3 but later will grow) and separated Puppet CA. Puppet CA don't acts as master even to himself. Puppet Masters are Katello Capsules and have published some Puppet environments and **a lot** of YUM content. Client specify environment when asking CA even if do it through proxy. In this case I have some choices:
1. Publish all environments and YUM content on Puppet CA. **Bad idea.**
2. Periodically sync environments from one of Puppet Masters. **Not good.**
3. Replace environment to the existing one on Puppet CA when proxying CA requests on the Capsules. In  this case we are losing the ability to process CA requests differently for different environments. But this case may be reasonable when using 2 or more intermediate CA and the proxy should determine to which CA proxy requests. Module don't handle this case now so this is **best** solution **for me**.

**Comment by discreet** [comment]
@aleksey-novikov I am in a load balanced environment (4 puppet masters and 2 puppet ca's) and am not experiencing the issue you are describing. I am not running a full Katello implementation however though I doubt there would be a difference.

**Comment by aleksey-novikov** [comment]
@discreet Do you have **all** environments used by nodes on Puppet CA or node agent's puppet.conf environment setting points to some existing environment like 'production' which differ from environment setting stored in ENC?

**Comment by discreet** [comment]
@aleksey-novikov My Puppet CA servers only have the default environments on them (common, development, production). My Puppet Servers (masters) have all environments (common, demo, development, integration, production, qa, stage, test) and the agent's puppet.conf only includes the environment for that particular host.

**Comment by aleksey-novikov** [comment]
@discreet Let host's environment is to `test` in the `puppet.conf`.  Now, let remove hosts cert and keys and ask CA for new one.
Using standard configuration we have some request on CA:
```
GET /test/certificate/ca?fail_on_404=true
GET /test/certificate/<host_fqdn>?
GET /test/certificate_request/<host_fqdn>?
PUT /test/certificate_request/<host_fqdn>
```
You will see following errors:
`Could not request certificate: Find /test/certificate/ca?fail_on_404=true resulted in 404 with the message: Not Found: Could not find environment 'test'`

**Comment by discreet** [comment]
@aleksey-novikov it sounds like you might not have the environment in Foreman. I have hosts in environments that do not exist on my CA servers and have no issues, even with new deploys in said environments.

**Comment by aleksey-novikov** [comment]
@discreet May be your puppet master acts as intermediate CA? In this case you don't have any error.

**Comment by discreet** [comment]
@aleksey-novikov My Puppet masters serve no CA functions.

**Comment by aleksey-novikov** [comment]
@discreet Ok, tomorrow I will deploy new host and try to reproduce the case.

**Comment by aleksey-novikov** [comment]
@discreet Sorry, I can't deploy host at Friday, but I did it today (I replace Organization and Content View by `<org>` and `<content_view>` and so on).
1. Host's settings in foreman:
```
parameters:
  puppetmaster: sat-proxy1.<domain>
  puppet_ca: sat-ca.<domain>
  foreman_env: KT_<org>_Stable_<content_view>_14
environment: KT_<org>_Stable_<content_view>_14
```
2. Provisioning template puppet.conf left unchanged:
```
<%#
kind: snippet
name: puppet.conf
%>
[main]
<% if @host.operatingsystem.name == 'FreeBSD' -%>
vardir = /var/puppet
logdir = \$vardir/log
<% else -%>
vardir = /var/lib/puppet
logdir = /var/log/puppet
<% end -%>
rundir = /var/run/puppet
ssldir = \$vardir/ssl

[agent]
pluginsync      = true
report          = true
ignoreschedules = true
daemon          = false
<%- if @host.puppet_ca_server.strip != '' -%>
ca_server       = <%= @host.puppet_ca_server %>
<%- end -%>
certname        = <%= @host.certname %>
environment     = <%= @host.environment %>
server          = <%= @host.puppetmaster %>

```
3. When provisioning reach the step `/usr/bin/puppet agent --config /etc/puppet/puppet.conf -o -t <%= @host.puppetmaster.blank? ? '' : "--server #{@host.puppetmaster}" %> --no-daemonize`
we can see errors on client:
```
Info: creating new SSL key for <host>
Error: Could not request certificate: Find /KT_<org>_Stable_<content_view>_14/certificate/ca?fail_on_404=true resulted 404 with message: Not Found: Could not find environment 'KT_<org>_Stable_<content_view>_14'

```
on CA in puppet_access_log we can see
`<Client IP> - - [21/Mar/2016:11:58:52 +0300] "GET /KT_<org>_Stable_<content_view>_14/certificate/ca?fail_on_404=true HTTP/1.1" 404 75 "-" "Ruby"`

**Comment by mmoll** [comment]
I'm inclined to merge this, although I have no environment to test this (@brandonweeks, @discreet, could you test that?). Anybody else any objections?

**Comment by ekohl** [comment]
Doesn't this break functionality for all environments other than production?

**Comment by discreet** [comment]
@mmoll sorry it's been a crazy couple weeks. I unfortunately don't have an environment right now where i can test this. hopefully in a couple weeks if the need is still there i will have an environment back.

**Comment by mclueppers** [comment]
I can't reproduce this issue on my existing HA setup with Puppetserver 2.x. I have the default environment setup on my PuppetCA server yet requests for certs from nodes in other environments get thru.

```
[root@puppetca02 puppetserver]# tree -L 3 /etc/puppetlabs/code/
/etc/puppetlabs/code/
├── environments
│   └── production
│       ├── environment.conf
│       ├── hieradata
│       ├── manifests
│       └── modules
└── modules

6 directories, 1 file
```

puppetserver-access.log
```
X.X.X.X - - [19/Oct/2016:14:00:53 +0000] "GET /puppet-ca/v1/certificate/bsview56.domain.ext?environment=production& HTTP/1.1" 200 1976 "-" "Ruby" 7
X.X.X.X - - [19/Oct/2016:14:00:54 +0000] "GET /puppet-ca/v1/certificate_revocation_list/ca?environment=production& HTTP/1.1" 200 245082 "-" "Ruby" 39
X.X.X.X - - [19/Oct/2016:14:00:56 +0000] "GET /puppet-ca/v1/certificate/ca?environment=production&fail_on_404=true HTTP/1.1" 200 1996 "-" "Ruby" 14
X.X.X.X - - [19/Oct/2016:15:16:19 +0000] "GET /development/certificate/ca?fail_on_404=true HTTP/1.1" 200 1996 "-" "Ruby" 13
X.X.X.X - - [19/Oct/2016:15:16:19 +0000] "GET /development/certificate/tstsrvbs01.domain.ext? HTTP/1.1" 404 55 "-" "Ruby" 6
X.X.X.X - - [19/Oct/2016:15:16:20 +0000] "GET /development/certificate_request/tstsrvbs01.domain.ext? HTTP/1.1" 404 63 "-" "Ruby" 3
X.X.X.X - - [19/Oct/2016:15:16:20 +0000] "PUT /development/certificate_request/tstsrvbs01.domain.ext HTTP/1.1" 200 0 "-" "Ruby" 186
X.X.X.X - - [19/Oct/2016:15:16:21 +0000] "GET /development/certificate/tstsrvbs01.domain.ext? HTTP/1.1" 200 1980 "-" "Ruby" 6
X.X.X.X - - [19/Oct/2016:15:16:22 +0000] "GET /development/certificate_revocation_list/ca? HTTP/1.1" 200 245176 "-" "Ruby" 29
```

**Comment by ekohl** [comment]
I'm going to close this issue since we can't reproduce this. Feel free to reopen this if you have steps to reproduce it.

@mclueppers thanks for testing this!

**Comment by pulecp** [comment]
I got to the same issue. I fixed that by $environments parameter (https://github.com/theforeman/puppet-puppet/blob/master/manifests/server.pp#L93). I pass the array of all environments I use. Puppet creates the proper directories for me under _/etc/puppet/environments/_

**Pull request closed without merging**
