### PR TITLE
assume version 2.5.0 of puppetserver

### PR DESCRIPTION
**Pull request by mmoll**
closes GH-423

### CODE REVIEW

**Comment by ekohl** [comment]
:+1: test failure is unrelated

**Comment by mmoll** [comment]
also updated the README now

**Comment by domcleal** [comment]
:+1: also once tests are sorted (msync in progress).

**Comment by mmoll** [comment]
should turn :green_heart:

**Comment by domcleal** [comment]
Merged, thanks @mmoll.

**Pull request merged**
