### PR TITLE
Correct $puppetrun_cmd on Linux

### PR DESCRIPTION
**Pull request by ekohl**
Regression introduced in f74e45d1dc8a96929f22733f39052a798aeff52f.

### CODE REVIEW

**Comment by mmoll** [comment]
I'm leaning towards merging, even if tests on Puppet 2.7 are failing. I suppose the current stdlib master is not 2.7 compatible anymore?

**Comment by ekohl** [comment]
I agree. We can pin stdlib in a separate PR. Most likely we need to do the same in foreman-installer.

**Comment by mmoll** [comment]
bedankt @ekohl!

**Comment by ekohl** [comment]
Geen dank :)

**Pull request merged**
