### PR TITLE
Added RedHat 5 to $osreleasemajor conditionals

### PR DESCRIPTION
**Pull request by szynaka**

### CODE REVIEW

**Comment by ekohl** [comment]
I don't have an EL5 install at hand, but it looks like it makes sense.

**Comment by mmoll** [comment]
EL5 is unsupported, according by metadata.json and we don't test it in any way. While I'm not against merging this, the status of 5 is questionable.

**Comment by szynaka** [comment]
Michael,
  I hadn't checked the metadata.json before submitting.  Feel free to
ignore it if you wish, as I know how bad it can be to try to support an OS
you don't have locally.  I originally fixed it on my end through Hiera data
but thought it was an easy enough fix I'd submit a pull.

Ed

**Comment by mmoll** [comment]
@szynaka as said, I'm not against merging this... I suppose you're running this module with EL5 nodes happily?

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
