### PR TITLE
Fix reporting when running under puppet AIO installs

### PR DESCRIPTION
**Pull request by ekohl**
This follows the discussion in https://github.com/theforeman/puppet-foreman/pull/398.

### CODE REVIEW

**Comment by mmoll** [comment]
looking good, merged. bedankt @ekohl!

**Comment by ekohl** [comment]
I just realized I might have pushed the wrong version. This resolves to ```/opt/puppetlabs/puppet/lib/ruby/site_ruby/2.1.0/puppet``` instead of ```/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet```.

**Comment by mmoll** [comment]
true, but it still sends the report :)

**Comment by ekohl** [comment]
I think it didn't for me and I needed to place it in vendor_ruby.

**Comment by mmoll** [comment]
fixed in #354, in the location of that PR, a report was sent but without contents

**Pull request merged**
