### PR TITLE
Unpin voxpupuli/extlib

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by ekohl** [comment]
I assume this was pinned because of Ruby 1.8.7

**Comment by domcleal** [comment]
> I assume this was pinned because of Ruby 1.8.7

That's right, 1.0.0 dropped (broke) support, but otherwise it contains few changes at the moment.

**Comment by ekohl** [comment]
:+1: on green tests

**Comment by mmoll** [comment]
merged, thanks @domcleal!

**Pull request merged**
