### PR TITLE
Full interface for apache::mod::passenger

### PR DESCRIPTION
**Pull request by dmichelotto**
Added full interface for apache::mod::passenger, in order to permit passenger fine tuning

### CODE REVIEW

**Comment by ekohl** [comment]
We try not to manage ```apache::mod::passenger```. The preferred way is to configure it yourself and do that before including puppet-puppet.

**Comment by mmoll** [comment]
Please see #294 and #310 for further information.

**Comment by mmoll** [comment]
Regarding #294, #310 and #333:

I'm leaning towards closing this. As we are using `apache::mod::passenger` also in theforeman-puppet (and very often in the same catalogs), we can't really expose any parameters there.

As we already (not 100% complete but mostly) are supporting puppetserver 1 and will be supporting puppetserver 2 (see #343, there's more work in progress right now to get all parts of Foreman 1.12 fully compatible with Puppet 4, also AIO packaged) I suggest to look at puppetserver if there are performance problems with puppetmaster.

However, if anybody is willing to implement this with custom templates, we for sure will have a look on that, although [ersonally I just don't think the time invest is worth it, especially with Puppet 4 fully deprecating the Ruby based puppetmaster for the CLJ/JVM based puppetserver.

Let me know what you are thinking about this...

**Comment by ekohl** [comment]
I agree with this. As I stated before, we try not to touch apache::mod::apache and leave that up to the user (either in a profile module or through data bindings). Puppet moving away from passenger to puppet server even makes this more logical.

**Pull request closed without merging**
