### PR TITLE
modulesync: enable future parser tests

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by mmoll** [comment]
rebased.

**Comment by mmoll** [comment]
Fixed some tests, maybe somebody else could have a look onto the apache/rack thing still failing?

There are quite some module parts untested, so even if all the tests suceed, the module will not really be future_parser ready.

However, I think we should just bring that in so at least new PRs with tests will have an indicator about it.

**Comment by ekohl** [comment]
I don't know if this change works, but let's see what Travis says.

**Comment by ekohl** [comment]
Looks like ```$puppet::server_app_root``` isn't set. This can be solved through a pre_condition in the tests.

**Comment by mmoll** [comment]
Solved this by using rspec-puppet-facts also there, should turn :green_heart:

**Comment by mmoll** [comment]
mispushed there :(
but the PR tests are green.

**Comment by mmoll** [comment]
rebased.

**Comment by domcleal** [comment]
:+1: from me.

**Comment by ekohl** [comment]
Minor comments inline. :+1: for the general change.

**Comment by domcleal** [comment]
Fixed the indentation and removed the check for EL6, it now runs on all OSes.

**Comment by domcleal** [comment]
And fails on all OSes due to the app_root being missing, curious.  Will investigate more soon.

I don't think the conditional here was working reliably (maybe r-p-f version differences): https://github.com/domcleal/puppet-puppet/commit/472b6002cf348e80ef8919026befddee456ec546#diff-2192e49e7ea16301b4ba87a40eeb3a86R5 as the previous run (https://travis-ci.org/domcleal/puppet-puppet/jobs/64176632) doesn't seem to have run any tests from that class.

**Comment by ekohl** [comment]
That is the same error we saw as before the if check. I wonder if the tests were even executed or we just masked it.

**Comment by ekohl** [comment]
I still think the spec needs a pre-condition which includes the main puppet class so the variable is set.

**Comment by domcleal** [comment]
> I still think the spec needs a pre-condition which includes the main puppet class so the variable is set.

I agree that'd work.  I took a slightly different route, which was to parameterise puppet::server::rack and explicitly initialise it, is that OK?

**Comment by ekohl** [comment]
:+1:

**Comment by mmoll** [comment]
Thank You, Gentlemen!
:clap:

**Pull request merged**
