### PR TITLE
Fixes #29735 - support el8

### PR DESCRIPTION
**Pull request by wbclark**

### CODE REVIEW

**Comment by ekohl** [comment]
This may fail since it uses `PIDFile` in the systemd unit and as we've seen in other cases, that doesn't work in Docker testing :(

**Comment by wbclark** [comment]
> This may fail since it uses `PIDFile` in the systemd unit and as we've seen in other cases, that doesn't work in Docker testing :(

I thought that may be the case when I saw no el7 in travis config. I'm running the puppetserver_latest_spec.rb on an el8 VM and getting errors in puppet apply:

Failures:

  1) Scenario: install puppetserver (latest): behaves like a idempotent resource applies with no errors
     Failure/Error: apply_manifest(pp, catch_failures: true)
     Beaker::Host::CommandFailure:
       Host 'centos8-64-1' exited with 1 running:
        puppet apply --verbose --detailed-exitcodes /tmp/apply_manifest.pp.dyYRf3
       Last 10 lines of output were:
       	Error: Evaluation Error: Error while evaluating a Resource Statement, Could not find declared class ::puppet (file: /tmp/apply_manifest.pp.dyYRf3, line: 1, column: 5) on node centos8-64-1
       
     Shared Example Group: "a idempotent resource" called from ./spec/acceptance/puppetserver_latest_spec.rb:31
     # /usr/share/gems/gems/beaker-4.22.1/lib/beaker/host.rb:395:in `exec'
     # /usr/share/gems/gems/beaker-4.22.1/lib/beaker/dsl/helpers/host_helpers.rb:83:in `block in on'
     # /usr/share/gems/gems/beaker-4.22.1/lib/beaker/shared/host_manager.rb:130:in `run_block_on'
     # /usr/share/gems/gems/beaker-4.22.1/lib/beaker/dsl/patterns.rb:37:in `block_on'
     # /usr/share/gems/gems/beaker-4.22.1/lib/beaker/dsl/helpers/host_helpers.rb:63:in `on'
     # /usr/share/gems/gems/beaker-puppet-1.19.1/lib/beaker-puppet/helpers/puppet_helpers.rb:529:in `block in apply_manifest_on'
     # /usr/share/gems/gems/beaker-4.22.1/lib/beaker/shared/host_manager.rb:130:in `run_block_on'
     # /usr/share/gems/gems/beaker-4.22.1/lib/beaker/dsl/patterns.rb:37:in `block_on'
     # /usr/share/gems/gems/beaker-puppet-1.19.1/lib/beaker-puppet/helpers/puppet_helpers.rb:457:in `apply_manifest_on'
     # /usr/share/gems/gems/beaker-puppet-1.19.1/lib/beaker-puppet/helpers/puppet_helpers.rb:536:in `apply_manifest'
     # ./spec/spec_helper_acceptance.rb:25:in `block (2 levels) in <top (required)>'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:257:in `instance_exec'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:257:in `block in run'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:503:in `block in with_around_and_singleton_context_hooks'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:460:in `block in with_around_example_hooks'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:481:in `block in run'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:619:in `run_around_example_hooks_for'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:481:in `run'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:460:in `with_around_example_hooks'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:503:in `with_around_and_singleton_context_hooks'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:254:in `run'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:644:in `block in run_examples'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:640:in `map'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:640:in `run_examples'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:606:in `run'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:607:in `block in run'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:607:in `map'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:607:in `run'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:121:in `map'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/configuration.rb:2058:in `with_suite_hooks'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/reporter.rb:74:in `report'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:115:in `run_specs'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:89:in `run'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:71:in `run'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:45:in `invoke'
     # /usr/share/gems/gems/rspec-core-3.9.2/exe/rspec:4:in `<top (required)>'
     # /usr/bin/rspec:23:in `load'
     # /usr/bin/rspec:23:in `<top (required)>'
     # /usr/share/gems/gems/bundler-1.17.2/lib/bundler/cli/exec.rb:74:in `load'
     # /usr/share/gems/gems/bundler-1.17.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
     # /usr/share/gems/gems/bundler-1.17.2/lib/bundler/cli/exec.rb:28:in `run'
     # /usr/share/gems/gems/bundler-1.17.2/lib/bundler/cli.rb:463:in `exec'
     # /usr/share/gems/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     # /usr/share/gems/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
     # /usr/share/gems/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
     # /usr/share/gems/gems/bundler-1.17.2/lib/bundler/cli.rb:27:in `dispatch'
     # /usr/share/gems/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
     # /usr/share/gems/gems/bundler-1.17.2/lib/bundler/cli.rb:18:in `start'
     # /usr/share/gems/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
     # /usr/share/gems/gems/bundler-1.17.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
     # /usr/share/gems/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
     # /usr/bin/bundle:23:in `load'
     # /usr/bin/bundle:23:in `<main>'

  2) Scenario: install puppetserver (latest): behaves like a idempotent resource applies a second time without changes
     Failure/Error: apply_manifest(pp, catch_changes: true)
     Beaker::Host::CommandFailure:
       Host 'centos8-64-1' exited with 1 running:
        puppet apply --verbose --detailed-exitcodes /tmp/apply_manifest.pp.woMNUW
       Last 10 lines of output were:
       	Error: Evaluation Error: Error while evaluating a Resource Statement, Could not find declared class ::puppet (file: /tmp/apply_manifest.pp.woMNUW, line: 1, column: 5) on node centos8-64-1
       
     Shared Example Group: "a idempotent resource" called from ./spec/acceptance/puppetserver_latest_spec.rb:31
     # /usr/share/gems/gems/beaker-4.22.1/lib/beaker/host.rb:395:in `exec'
     # /usr/share/gems/gems/beaker-4.22.1/lib/beaker/dsl/helpers/host_helpers.rb:83:in `block in on'
     # /usr/share/gems/gems/beaker-4.22.1/lib/beaker/shared/host_manager.rb:130:in `run_block_on'
     # /usr/share/gems/gems/beaker-4.22.1/lib/beaker/dsl/patterns.rb:37:in `block_on'
     # /usr/share/gems/gems/beaker-4.22.1/lib/beaker/dsl/helpers/host_helpers.rb:63:in `on'
     # /usr/share/gems/gems/beaker-puppet-1.19.1/lib/beaker-puppet/helpers/puppet_helpers.rb:529:in `block in apply_manifest_on'
     # /usr/share/gems/gems/beaker-4.22.1/lib/beaker/shared/host_manager.rb:130:in `run_block_on'
     # /usr/share/gems/gems/beaker-4.22.1/lib/beaker/dsl/patterns.rb:37:in `block_on'
     # /usr/share/gems/gems/beaker-puppet-1.19.1/lib/beaker-puppet/helpers/puppet_helpers.rb:457:in `apply_manifest_on'
     # /usr/share/gems/gems/beaker-puppet-1.19.1/lib/beaker-puppet/helpers/puppet_helpers.rb:536:in `apply_manifest'
     # ./spec/spec_helper_acceptance.rb:29:in `block (2 levels) in <top (required)>'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:257:in `instance_exec'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:257:in `block in run'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:503:in `block in with_around_and_singleton_context_hooks'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:460:in `block in with_around_example_hooks'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:481:in `block in run'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:619:in `run_around_example_hooks_for'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:481:in `run'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:460:in `with_around_example_hooks'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:503:in `with_around_and_singleton_context_hooks'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:254:in `run'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:644:in `block in run_examples'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:640:in `map'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:640:in `run_examples'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:606:in `run'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:607:in `block in run'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:607:in `map'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:607:in `run'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:121:in `map'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/configuration.rb:2058:in `with_suite_hooks'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/reporter.rb:74:in `report'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:115:in `run_specs'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:89:in `run'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:71:in `run'
     # /usr/share/gems/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:45:in `invoke'
     # /usr/share/gems/gems/rspec-core-3.9.2/exe/rspec:4:in `<top (required)>'
     # /usr/bin/rspec:23:in `load'
     # /usr/bin/rspec:23:in `<top (required)>'
     # /usr/share/gems/gems/bundler-1.17.2/lib/bundler/cli/exec.rb:74:in `load'
     # /usr/share/gems/gems/bundler-1.17.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
     # /usr/share/gems/gems/bundler-1.17.2/lib/bundler/cli/exec.rb:28:in `run'
     # /usr/share/gems/gems/bundler-1.17.2/lib/bundler/cli.rb:463:in `exec'
     # /usr/share/gems/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     # /usr/share/gems/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
     # /usr/share/gems/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
     # /usr/share/gems/gems/bundler-1.17.2/lib/bundler/cli.rb:27:in `dispatch'
     # /usr/share/gems/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
     # /usr/share/gems/gems/bundler-1.17.2/lib/bundler/cli.rb:18:in `start'
     # /usr/share/gems/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
     # /usr/share/gems/gems/bundler-1.17.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
     # /usr/share/gems/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
     # /usr/bin/bundle:23:in `load'
     # /usr/bin/bundle:23:in `<main>'

Finished in 7.22 seconds (files took 1 minute 10.11 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./spec/acceptance/puppetserver_latest_spec.rb[1:1:1] # Scenario: install puppetserver (latest): behaves like a idempotent resource applies with no errors
rspec ./spec/acceptance/puppetserver_latest_spec.rb[1:1:2] # Scenario: install puppetserver (latest): behaves like a idempotent resource applies a second time without changes

**Comment by wbclark** [comment]
Looks like I just forgot to run spec prep, will try that again

**Comment by wbclark** [comment]
spec/acceptance/puppetserver_{config,latest}_spec.rb are passing for me on a vagrant libvirt VM with no additional changes.

I'm assuming spec/acceptance/puppetserver_upgrade*.rb is not important for el8 support since users shouldn't have an older version installed on the newly supported OS.

@ekohl therefore I removed everything except marking the OS supported in metadata. could you take a look and let me know if there is anything else that should be touched before we move forward?

**Comment by ekohl** [comment]
> I'm assuming spec/acceptance/puppetserver_upgrade*.rb is not important for el8 support since users shouldn't have an older version installed on the newly supported OS.

EL8 has been out for a while now. However, the specific versions we're testing might not be available. It does happen that you need to update from one minor version to the next and it should handle that. Sadly there can be incompatible changes to the files and that is what it's intended to cover.

**Pull request merged**
