### PR TITLE
Correct Type Validation of server_foreman_ssl*

### PR DESCRIPTION
**Pull request by jstewart612**
The upstream ::foreman::puppetmaster class correctly allows empty strings for these parameters for Foreman instances that don't require mutual TLS authentication for this purpose.  The change is already made there.  Just matching it here.

### CODE REVIEW

**Comment by ekohl** [comment]
Thanks! I'll just let Travis finish before merging.

**Comment by jstewart612** [comment]
@ekohl found another spot where it needed updating so sorry Travis will run again I imagine XD

**Comment by jstewart612** [comment]
Found more issues on my side, will close and resubmit when more complete

**Comment by stefanlasiewski** [comment]
@jstewart612 Was this ever resubmitted in a different PR?

**Comment by jstewart612** [comment]
@stefanlasiewski no

**Pull request closed without merging**
