### PR TITLE
Don't configure defaults environments if directory_environment is set

### PR DESCRIPTION
**Pull request by mcanevet**

### CODE REVIEW

**Comment by mmoll** [comment]
looking good visually :+1:

**Comment by domcleal** [comment]
I don't think this behaviour should be changed, it is deliberate that we set up the environments in $server_environments whether you're using directory envs or config envs (they were written to be equivalent where possible).

What's the reason you're changing it, it might help me understand what might need to change?

**Comment by jlambert121** [comment]
I was going to write a PR for this as well, but it looks like it's already here.  We manage out environments with r10k outside of any modules, puppet creates these environments for us and then r10k removes them causing a "change" on the next puppet run.

**Comment by mmoll** [comment]
Maybe this can get wrapped into an extra parameter?
Also, this needs a rebase :)

**Comment by mmoll** [comment]
what's the status here?

**Comment by mcanevet** [comment]
@mmoll I think we can close this as we don't use this module anymore

**Comment by mmoll** [comment]
@mcanevet sorry to hear that :cry:
@jlambert121 feel free to open a new PR about this

**Comment by jlambert121** [comment]
#348

**Pull request closed without merging**
