### PR TITLE
allow the user to add custom auth rules in auth.conf without managing the entire template

### PR DESCRIPTION
**Pull request by cristifalcas**
File "${puppet_dir}/auth.conf" was modified to concat resource.
Added a new define puppet::auth.
Update tests.

Usage: 

		  puppet::auth { 'allow all machines to upload their own facts':
		    path   => '/facts/',
		    method => 'save, find, search',
		    auth   => 'yes',
		    allow  => '*',
		  }

### CODE REVIEW

**Comment by domcleal** [comment]
This seems reasonable on the surface, but I don't think it's going to do anything in a Puppet Server configuration as the HOCON auth config is used by default (in this module).

I think the level of abstraction needs to be higher to cover both the old auth.conf and the HOCON version (i.e. #439).

**Comment by cristifalcas** [comment]
But it doesn't change the current status, no?

We are not using puppet 4 yet, so I don't know how to manage the HOCON config.

**Comment by mmoll** [comment]
We do try to manage both configs from the same "source data" in this module, if possible, so this does make a difference right now.

**Comment by cristifalcas** [comment]
It will be acceptable to do the same thing (with concat) for HOCON config?

**Comment by cristifalcas** [comment]
It will be acceptable to do the same thing (with concat) for HOCON config?

**Comment by mmoll** [comment]
@cristifalcas as long as it works correctly I'd say yes, as that would hopefully allow us to refactor further later to have easier possibilities to construct/add auth rules for both formats in order to support HA configurations better.

**Comment by mmoll** [comment]
closing due to inactivity, this module is puppet 4.x only in current master now

**Pull request closed without merging**
