### PR TITLE
Drop Puppet 6 support

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ehelms** [comment]
Mind cleaning up the README as well? There are few mentions of lowest supported version and an upgrade guide that is no longer relevant.

**Comment by ekohl** [comment]
Good point. Updated and made some adjustments to the tests to make them pass.

**Comment by ekohl** [comment]
All green now.

**Comment by evgeni** [comment]
you didn't remove enough lines :stuck_out_tongue_closed_eyes: 

https://github.com/theforeman/puppet-puppet/blob/5050652f64b04025eb497c707c3c5c4275b0ccd8/.fixtures.yml#L5
https://github.com/theforeman/puppet-puppet/blob/5050652f64b04025eb497c707c3c5c4275b0ccd8/.fixtures.yml#L9
https://github.com/theforeman/puppet-puppet/blob/2ef1b869e9f2542f6a80cd7837749168d0537eff/spec/acceptance/puppetserver_upgrade_spec.rb#L20
https://github.com/theforeman/puppet-puppet/blob/2ef1b869e9f2542f6a80cd7837749168d0537eff/spec/acceptance/puppetserver_upgrade_spec.rb#L29
https://github.com/theforeman/puppet-puppet/blob/2ef1b869e9f2542f6a80cd7837749168d0537eff/spec/support/acceptance/puppetserver.rb#L10
https://github.com/theforeman/puppet-puppet/blob/2ef1b869e9f2542f6a80cd7837749168d0537eff/manifests/server.pp#L271

**Review by evgeni — APPROVED** [review]
https://github.com/theforeman/puppet-puppet/blob/2ef1b869e9f2542f6a80cd7837749168d0537eff/manifests/init.pp#L574

I think that's the last one, but also kinda unimportant :)

**Comment by ekohl** [comment]
Now also with https://github.com/puppetlabs/puppetserver/commit/240a4590d304016314088184a18b9ba9c51c3d2c

**Pull request merged**
