### PR TITLE
Fix missing default parameters for strict variable tests

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by ekohl** [comment]
It appears the FreeBSD and Windows tests still fail

**Comment by domcleal** [comment]
Thanks, I think I've fixed that now by defining server_puppetserver_* related parameter defaults for FreeBSD and Windows - set to `undef` where n/a.

**Comment by ekohl** [comment]
:+1: on green tests

**Comment by mmoll** [comment]
merged, thanks @domcleal!

**Pull request merged**
