### PR TITLE
Bump version to 16.0.0

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
I had hoped to drop more things in the major release but we're out of time. Things such as:
* EL6 (https://github.com/theforeman/puppet-puppet/pull/785)
* Puppet 5 (https://github.com/theforeman/puppet-puppet/pull/791)

I'm slightly leaning to releasing 15.2.0 with just #804 and keep the major release for later. Thoughts?

**Comment by ehelms** [comment]
> I had hoped to drop more things in the major release but we're out of time. Things such as:
> 
> * EL6 (#785)
> * Puppet 5 (#791)
> 
> I'm slightly leaning to releasing 15.2.0 with just #804 and keep the major release for later. Thoughts?

I would be OK with that. That would mean we:

 * cut a 15.2-stable branch
 * Bump master to 16.0.0

Sound right?

**Comment by ekohl** [comment]
Exactly that

**Comment by ehelms** [comment]
This is now a PR to just bump the version

**Review by ekohl — APPROVED** [review]

**Pull request merged**
