### PR TITLE
Remove dynamic and config environments

### PR DESCRIPTION
**Pull request by ekohl**
Since Puppet 4 only directory environments are supported so this was mostly dead code.

### CODE REVIEW

**Comment by ekohl** [comment]
Rephrased. I did consider keeping the env defined type but chose not to in favor of recommending people to store these files in git and deploy either with our git repo (should still work I think) or tools like r10k.

**Comment by mmoll** [comment]
@ekohl needs a rebase and fixing

**Comment by ekohl** [comment]
Rebased

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
