### PR TITLE
Test for the correct line endings on Windows

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by mmoll** [comment]
`spec/classes/puppet_config_spec.rb` probably also needs a modification.

**Comment by ekohl** [comment]
This is quite ugly but IMHO less ugly than the alternative of including `\r?\n`. Note that `$` also doesn't work because there's a `\r` there. Not sure if there's a better way.

**Comment by mmoll** [comment]
it's :green_heart:

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
