### PR TITLE
Allow Puppet 7 compatible versions of mods

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by timdeluxe** [comment]
@ekohl Why did you not raise systemd dependency?

**Comment by ekohl** [comment]
Because that's really a breaking change and I'm still looking at that. The title was a bit misleading, but it's on my radar.

**Comment by timdeluxe** [comment]
Okay, we need that to fit in dependencies. I will fork, raise by myself, but not raise a PR, because it is on your radar. However i can report if we experience any issues due to that, if you are interested.

**Comment by ekohl** [comment]
That should be https://github.com/theforeman/puppet-puppet/pull/790. I'll probably prepare the PRs for all other modules prior to merging it and verify our installer still works completely.

**Pull request merged**
