### PR TITLE
Make theforeman/git a soft dependency

### PR DESCRIPTION
**Pull request by domcleal**
Following the change for theforeman/foreman and puppetlabs/puppetdb.

### CODE REVIEW

**Comment by mmoll** [comment]
:+1:, would be nice to link puppet-git in the README

**Comment by domcleal** [comment]
Ah yes, which reminds me, shall I link to the Puppet Forge page do you think rather than the GitHub repo?

**Comment by mmoll** [comment]
Personally I would link the forge page, but it seems that gitrepo is the standard at the moment.

**Comment by domcleal** [comment]
Hopefully that's standardised properly now  :)

**Comment by mmoll** [comment]
yes, thanks @domcleal!

**Pull request merged**
