### PR TITLE
set hiera_config correctly on puppet 4

### PR DESCRIPTION
**Pull request by mmckinst**
This was changed in puppet 3 vs 4:

puppet 3: https://docs.puppetlabs.com/puppet/3/reference/configuration.html#hieraconfig
puppet 4: https://docs.puppetlabs.com/puppet/latest/reference/configuration.html#hieraconfig

### CODE REVIEW

**Comment by ekohl** [comment]
The tests are failing, other than that the change looks good.

**Comment by mmckinst** [comment]
the failing tests appears to be due to ruby 1.8.7 and bundler no longer being compatible with it

**Comment by ekohl** [comment]
:+1:

**Comment by mmoll** [comment]
merged as e5f0423, thanks @mmckinst!

**Pull request closed without merging**
