### PR TITLE
Drop support for puppetserver < 2.7

### PR DESCRIPTION
**Pull request by ekohl**
Includes https://github.com/theforeman/puppet-puppet/pull/648

### CODE REVIEW

**Comment by ekohl** [comment]
Rebased and I think this is now ready for merge.

**Comment by mmoll** [comment]
@ekohl do we want to create a 10.0-stable branch now? :)

**Comment by ekohl** [comment]
Probably. Another change I'm thinking about is moving the puppetserver version detection logic into `puppet::server::puppetserver` so we don't store the value in the installer's answer files to ease upgrading.

**Comment by mmoll** [comment]
@ekohl needs a rebase

**Comment by ekohl** [comment]
Rebased

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
