### PR TITLE
Bump requirement of puppet to 3.1.0 and drop namespaceauth.conf.

### PR DESCRIPTION
**Pull request by tdevelioglu**
Replace `rescue` with `||` in namespaceauth template as it was probably intended.

### CODE REVIEW

**Comment by mmoll** [comment]
While I see no problem with this change as such, AFAICT, this file is obsolete since Puppet 3.1, maybe it's time (also see the autosign section discussion in #375) to raise the minimum Puppet version of this module to 3.1.0 and delete namespaceauth.conf handling?

May I ask how you stumbled across this?

**Comment by tdevelioglu** [comment]
By chance while doing a grep for something else. I'd remove it for sure if everyone's ok with bumping to 3.1+.

**Comment by mmoll** [comment]
I would be OK with this.

**Comment by domcleal** [comment]
Either's fine by me.

**Comment by brandonweeks** [comment]
+1 for bumping the minimum version.

**Comment by ekohl** [comment]
So who's going to bump the minimum version? :)

**Comment by mmoll** [comment]
Why not just add it to this PR?

**Comment by mmoll** [comment]
:+1:

**Comment by brandonweeks** [comment]
Progress! 👍

**Comment by domcleal** [comment]
Merged, thanks @tdevelioglu!

**Pull request merged**
