### PR TITLE
move default manifest creation to server config

### PR DESCRIPTION
**Pull request by SimonPe**
This only makes sense on a server

split out from #364

### CODE REVIEW

**Comment by ekohl** [comment]
:+1: on green tests.

**Comment by mmoll** [comment]
tests fail, I canceled the other testruns in the matrix to speed things up...

**Comment by SimonPe** [comment]
@mmoll yeah, i saw it, I'll have to move those tests from puppet_config_spec.rb to puppet_server_config_spec.rb (And it's actually my first time touching puppet tests :-) )

**Comment by SimonPe** [comment]
I updated the tests to only check the default_manifest when server => true. they are passing now locally.

**Comment by mmoll** [comment]
merged, bedankt @SimonPe!

**Pull request closed without merging**
