### PR TITLE
Release 15.1.0

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ekohl** [comment]
Puppet 7 support has been merged. Please update

**Comment by ehelms** [comment]
Updated with Puppet 7 support

**Review by ekohl — APPROVED** [review]
Thoughts on at least building a nightly and running a pipeline before doing the release? I kicked off https://ci.theforeman.org/job/foreman-installer-develop-source-release/905/ at least.

**Comment by ehelms** [comment]
> Thoughts on at least building a nightly and running a pipeline before doing the release? I kicked off https://ci.theforeman.org/job/foreman-installer-develop-source-release/905/ at least.

Sure thing, I'll keep an eye on some that are running.

**Pull request merged**
