### PR TITLE
add puppetserver 2.7.x support

### PR DESCRIPTION
**Pull request by mmoll**
cherry-picked for 6.0-stable

### CODE REVIEW

**Comment by domcleal** [comment]
I don't think this is strictly needed (2.6 mode works with 2.7), but it's OK if you'd like to.

**Comment by mmoll** [comment]
tbh, this time I didn't check if something breaks with the old config... if it's not needed I'd rather close this.

**Comment by domcleal** [comment]
It seems OK to me, the service runs and I can fetch and apply a catalog from it. I'm unsure about the gem_home change, but I can't see any impact from having the 2.6.0 configuration - it may define a default internally if it's even needed.

**Comment by mmoll** [comment]
allright, closing :)

**Pull request closed without merging**
