### PR TITLE
implement 'versioned code' for puppetserver

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
@ekohl If my changes are OK for you, I'll add tests.

**Comment by mmoll** [comment]
Ready for review.

**Comment by mmoll** [comment]
:green_heart:

**Comment by ekohl** [comment]
Thanks!

**Comment by bastelfreak** [comment]
hey @mmoll , do you by any chance use this and have working examples for the required scripts?

**Comment by mmoll** [comment]
@bastelfreak Sorry, nope... I just took up the PR of another user

**Pull request merged**
