### PR TITLE
Add yamldir and mode

### PR DESCRIPTION
**Pull request by mhjacks**
This is at the request of @mmoll.  Please critique and I will be happy to revise it.

### CODE REVIEW

**Comment by mmoll** [comment]
see theforeman/puppet-foreman#242 for background

**Comment by mmoll** [comment]
OK, after asking @mhjacks in IRC I think there was a miscommunication regarding the yamldir. the yamldir itself always was fine, so this PR is not needed, as this is handled by Puppet anyway: https://github.com/puppetlabs/puppet/blob/3.7.3/lib/puppet/defaults.rb#L1198-L1204
I guess this PR can get closed and we can proceed reviewing the original PR?

**Comment by mhjacks** [comment]
I have no objections if the project wishes to proceed that way.

**Comment by mmoll** [comment]
thanks, closing

**Pull request closed without merging**
