### PR TITLE
remove EOL OSes, add newer ones

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
waiting for a gem relase with https://github.com/camptocamp/facterdb/pull/52 included

**Comment by mmoll** [comment]
BTW, what should we do with Fedora?

**Comment by ekohl** [comment]
> BTW, what should we do with Fedora?

Good question. Since we don't really test it I have no idea if it actually works but that's also true for some of the other versions. Since I only see F24 and F25 RPMs on yum.puppetlabs.com I'd just list those.

**Comment by mmoll** [comment]
https://fedoramagazine.org/fedora-24-eol/

**Comment by ekohl** [comment]
Or just 25 then :)

**Comment by mmoll** [comment]
this should be ready now 💚

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
