### PR TITLE
[WIP] Set java security providers if needed

### PR DESCRIPTION
**Pull request by ekohl**
Will need to investigate if more distros need this and how to properly parametrize this.

### CODE REVIEW

**Comment by akofink** [comment]
It works fine on Ubuntu 16.04 with nightly.

**Comment by ekohl** [comment]
Odd, on a libvirt-based deployment this wasn't needed and reporting worked out of the box but on rackspace it was broken. Going to investigate further.

**Comment by ekohl** [comment]
It looks like systest is installing Puppet PC1 (4) which is an older puppetserver version. Going to set that to Puppet 5 and see if it's still an issue.

**Comment by ekohl** [comment]
Puppet 5 has solved this out of the box so it's no longer needed.

**Comment by akofink** [comment]
Great!

**Comment by ekohl** [comment]
https://github.com/theforeman/theforeman.org/pull/1041

**Pull request closed without merging**
