### PR TITLE
Added RedHat 5 to  conditionals

### PR DESCRIPTION
**Pull request by edestecd**
Can we have this in 4.3.2?  This seems like a regression that needs fixed.

### CODE REVIEW

**Comment by domcleal** [comment]
:+1:

**Comment by ekohl** [comment]
This is just a cherry-pick of 25e027c18c9b65745b3a0e85b3183ba45e24bb19 so :+1:

**Comment by brandonweeks** [comment]
Merged, thanks @edestecd!

**Comment by mmoll** [comment]
pushed 4.3.2 to the forge

**Pull request merged**
